# Generated by Django 2.2.14 on 2020-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
